global:
    scrape_interval: 100ms

scrape_configs:
    - job_name: 'prometheus'
      scrape_interval: 100ms
      static_configs:
          - targets: ['prometheus:9090']

    - job_name: 'pushgateway'
      honor_labels: true
      static_configs:
          - targets: ['prometheus-pushgateway:9091']